### ISSUE TITLE
[Bug] Error while loading script on Livesplit startup

### ISSUE THREAD

**Issue by Dev1neR** [just-ero/asl-help#8]
Whenever I launch livesplit while having the script manually added in layout, the error appears. If I reload script while livesplit is running, the error no longer exists. 

Livesplit error:
```
asl-help aborted due to a critical error! 

System.TypelnitializationException: The type initializer for 'AsIHelp.Data.AutoSplitter.Actions' threw an exception. -->
 System.TypelnitlalizationException: The type initializer for 'AslHelp.Data.AutoSplitter.Script threw an exception. —>
 System.NullReferenceException: Object reference not set to an Instance of an object. 
    at AslHelp.Extensions.ReflectionExt.GetAlIFields(Object obj, BindingFlags flags) 
    at AslHelp.Extensions.ReflectionExt.GetFieldValue[T](Object obj, String fieldName, BindingFlags flags) 
    at AslHelp.Data.AutoSplitter.Script.<>c.<.cctor>b__3_0(Object component) 
    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Funс`2 predicate) 
    at AslHelp.Data.AutoSplitter.Script..cctor() 
    — End of inner exception stack trace —
   at AslHelp.Data.AutoSplitter.Script.get_ASLScript()
   at AslHelp.Data.AutoSplitter.Actions..cctor()
    — End of inner exception stack trace —
   at AslHelp.Data.AutoSplitter.Actions.get_Current()
   at Basic.Startup(Boolean generateCode) 
```

The error that appears in debug monitor after hitting "OK":
```
Exception thrown: 'System.Reflection.TargetInvocationException' in 'startup' method:
Exception has been thrown by the target of an invocation.

   at ASL line 6 in 'startup'

   at LiveSplit.ASL.ASLMethod.Call(LiveSplitState timer, ExpandoObject vars, String& version, Double& refreshRate, Object settings, ExpandoObject old, ExpandoObject current, Process game)
   at LiveSplit.ASL.ASLScript.RunStartup(LiveSplitState state)
   at LiveSplit.UI.Components.ASLComponent.LoadScript()
```

The line 6 which is debug monitor referring to:
`vars.Helper = Assembly.Load(File.ReadAllBytes("Components/asl-help")).CreateInstance("Unity");`

**Comment by just-ero** [comment]
Could you try without `vars.Helper = `? So just;
```cs
startup
{
  Assembly.Load(File.ReadAllBytes("Components/asl-help")).CreateInstance("Unity");
}
```

**Comment by Dev1neR** [comment]
Same result without `vars.Helper =`
Feel free to take a look at the .asl: [Link](https://github.com/Dev1neR/ASLs/blob/main/FPSV3.asl)

**Comment by just-ero** [comment]
Was the other Scriptable Auto Splitter component using the same script? Was it using a different script which was also using the helper?

**Comment by Dev1neR** [comment]
The other auto splitter was using a different script and it wasn't using a helper.

**Comment by just-ero** [comment]
Please try with the current version. 5cd6ba76f89c8d1ec905b1fc790408d7a321b952 should have fixed this.

**Comment by Dev1neR** [comment]
Issue got fixed. Thank you!
